FROM golang as builder
COPY main.go .
COPY go.mod .
RUN go build

FROM ubuntu
COPY --from=builder /go/hello .
CMD ["./hello"]

# The WORKDIR in golang is /go, 
# The program path is really /go/hello.

# docker run hello-go:ubuntu
