FROM --platform=$BUILDPLATFORM golang as builder
COPY main.go .
COPY go.mod .
RUN go build 

FROM scratch
COPY --from=builder /go/hello .
CMD ["./hello"]

# docker run philippecharriere494/hello-go:multiarch